//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QLTGDDEntities : DbContext
    {
        public DB_QLTGDDEntities()
            : base("name=DB_QLTGDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_BangChamCong> tb_BangChamCong { get; set; }
        public virtual DbSet<tb_BANGCONG> tb_BANGCONG { get; set; }
        public virtual DbSet<tb_BANGCONGCHITIET> tb_BANGCONGCHITIET { get; set; }
        public virtual DbSet<tb_BANGLUONG> tb_BANGLUONG { get; set; }
        public virtual DbSet<tb_BANGLUONG_NHANVIEN> tb_BANGLUONG_NHANVIEN { get; set; }
        public virtual DbSet<tb_BANGLUONGCHINHANH> tb_BANGLUONGCHINHANH { get; set; }
        public virtual DbSet<tb_BCCT_NGAYCONG> tb_BCCT_NGAYCONG { get; set; }
        public virtual DbSet<tb_CHINHANH> tb_CHINHANH { get; set; }
        public virtual DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual DbSet<tb_DANHSO> tb_DANHSO { get; set; }
        public virtual DbSet<tb_DANHSOCHITIET> tb_DANHSOCHITIET { get; set; }
        public virtual DbSet<tb_HOPDONG> tb_HOPDONG { get; set; }
        public virtual DbSet<tb_LOAICONG> tb_LOAICONG { get; set; }
        public virtual DbSet<tb_NGAYCONGCHITET> tb_NGAYCONGCHITET { get; set; }
        public virtual DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual DbSet<tb_PHONGBAN> tb_PHONGBAN { get; set; }
        public virtual DbSet<tb_PHUCAP> tb_PHUCAP { get; set; }
        public virtual DbSet<tb_PHUCAP_NHANVIEN> tb_PHUCAP_NHANVIEN { get; set; }
        public virtual DbSet<tb_SANPHAM> tb_SANPHAM { get; set; }
        public virtual DbSet<tb_THANHTOAN> tb_THANHTOAN { get; set; }
        public virtual DbSet<tb_UNGLUONG> tb_UNGLUONG { get; set; }
    }
}
