//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BCCT_NGAYCONG
    {
        public int MABCCT { get; set; }
        public int MANCNV { get; set; }
        public Nullable<int> MALC { get; set; }
    
        public virtual tb_BANGCONGCHITIET tb_BANGCONGCHITIET { get; set; }
        public virtual tb_NGAYCONGCHITET tb_NGAYCONGCHITET { get; set; }
    }
}
