//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGCONGCHITIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BANGCONGCHITIET()
        {
            this.tb_BCCT_NGAYCONG = new HashSet<tb_BCCT_NGAYCONG>();
        }
    
        public int MABCCT { get; set; }
        public Nullable<int> MANCNV { get; set; }
        public Nullable<int> MABC { get; set; }
        public Nullable<double> SONGAYCONG { get; set; }
        public Nullable<double> TONGNGAYCONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<double> TONGNGAYCONGVANG { get; set; }
        public Nullable<double> TONGNGAYCONG1 { get; set; }
        public Nullable<double> TOINGNGAYPHEP { get; set; }
        public Nullable<double> TONGNGAYLE { get; set; }
        public Nullable<double> NGAYCONGTRONGTHANG { get; set; }
    
        public virtual tb_BANGCONG tb_BANGCONG { get; set; }
        public virtual tb_NGAYCONGCHITET tb_NGAYCONGCHITET { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BCCT_NGAYCONG> tb_BCCT_NGAYCONG { get; set; }
    }
}
