//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGLUONGCHINHANH
    {
        public int MABL { get; set; }
        public int MACN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual tb_BANGLUONG tb_BANGLUONG { get; set; }
        public virtual tb_CHINHANH tb_CHINHANH { get; set; }
    }
}
