//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGLUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BANGLUONG()
        {
            this.tb_BANGLUONG_NHANVIEN = new HashSet<tb_BANGLUONG_NHANVIEN>();
            this.tb_BANGLUONGCHINHANH = new HashSet<tb_BANGLUONGCHINHANH>();
        }
    
        public int MABL { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<double> TONGTIENLUONG { get; set; }
        public Nullable<System.DateTime> NGAYTINHLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BANGLUONG_NHANVIEN> tb_BANGLUONG_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BANGLUONGCHINHANH> tb_BANGLUONGCHINHANH { get; set; }
    }
}
