//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGLUONG_NHANVIEN
    {
        public int MABL { get; set; }
        public int MANV { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<int> MATT { get; set; }
        public Nullable<int> KHOA { get; set; }
    
        public virtual tb_BANGLUONG tb_BANGLUONG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        public virtual tb_THANHTOAN tb_THANHTOAN { get; set; }
    }
}
