//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NGAYCONGCHITET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NGAYCONGCHITET()
        {
            this.tb_BANGCONGCHITIET = new HashSet<tb_BANGCONGCHITIET>();
            this.tb_BCCT_NGAYCONG = new HashSet<tb_BCCT_NGAYCONG>();
        }
    
        public int MANCNV { get; set; }
        public Nullable<int> NGAY { get; set; }
        public string THU { get; set; }
        public string GIOIVAO { get; set; }
        public string GIOIRA { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> MALC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BANGCONGCHITIET> tb_BANGCONGCHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BCCT_NGAYCONG> tb_BCCT_NGAYCONG { get; set; }
        public virtual tb_LOAICONG tb_LOAICONG { get; set; }
    }
}
