//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NHANVIEN()
        {
            this.tb_BangChamCong = new HashSet<tb_BangChamCong>();
            this.tb_BANGCONGCHITIET = new HashSet<tb_BANGCONGCHITIET>();
            this.tb_BANGLUONG_NHANVIEN = new HashSet<tb_BANGLUONG_NHANVIEN>();
            this.tb_DANHSO = new HashSet<tb_DANHSO>();
            this.tb_HOPDONG = new HashSet<tb_HOPDONG>();
            this.tb_PHUCAP_NHANVIEN = new HashSet<tb_PHUCAP_NHANVIEN>();
            this.tb_UNGLUONG = new HashSet<tb_UNGLUONG>();
        }
    
        public int MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public byte[] HINHANH { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MAPB { get; set; }
        public Nullable<int> MACV { get; set; }
        public Nullable<int> MACN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BangChamCong> tb_BangChamCong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BANGCONGCHITIET> tb_BANGCONGCHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BANGLUONG_NHANVIEN> tb_BANGLUONG_NHANVIEN { get; set; }
        public virtual tb_CHINHANH tb_CHINHANH { get; set; }
        public virtual tb_CHUCVU tb_CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DANHSO> tb_DANHSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HOPDONG> tb_HOPDONG { get; set; }
        public virtual tb_PHONGBAN tb_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PHUCAP_NHANVIEN> tb_PHUCAP_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UNGLUONG> tb_UNGLUONG { get; set; }
    }
}
