//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHUCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PHUCAP()
        {
            this.tb_PHUCAP_NHANVIEN = new HashSet<tb_PHUCAP_NHANVIEN>();
        }
    
        public int MAPC { get; set; }
        public string TENPHUCAP { get; set; }
        public Nullable<double> SOTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PHUCAP_NHANVIEN> tb_PHUCAP_NHANVIEN { get; set; }
    }
}
